config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root "dashboard#home", as: :authenticated_root
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :posts do
    collection do
      get "new_form"
      get "pay"
      post "unlock"
    end
  end

  get :my_questions, to: "dashboard#my_questions"
  get :my_answers, to: "dashboard#my_answers"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  include AASM

  belongs_to :user

  scope :by_user, -> (user_id) { where(user_id: user_id) if user_id.present? }

  def self.search(params)
    search_posts = self.all
    search_posts
      .by_user(params[:user_id])
      .order(id: :desc)
      .limit(50)
  end

  aasm column: :status do
    state :locked, initial: true
    state :unlocked

    event :unlock do
      transitions from: :locked, to: :unlocked
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def lawyer?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def my_questions
  end

  def my_answers
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:unlock, :pay]

  def index
    @posts = Post.search(search_params)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def new_form
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html {redirect_to my_questions_path }
        format.turbo_stream {}
      end
    end
  end

  def delete
  end

  def unlock
    @post.unlock!

    respond_to do |format|
      if @post.unlocked?
        format.turbo_stream {}
      end
    end
  end

  def pay
  end

  private

  def post_params
    params.require(:post)
      .permit(:title, :body)
  end

  def search_params
    {user_id: params[:user_id]}
  end

  def find_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_color_from(string=nil)
    string ||= SecureRandom.hex[0..5]
    "#"+Digest::MD5.hexdigest(string)[0..5]
  end
end

app/helpers/flash_message_helper.rb
module FlashMessageHelper
  def getFlashColorClasses(type)
    case type.to_sym
    when :success
      { border: "border-green-400",
        icon: "fa-regular fa-circle-check text-green-400",
        title: "Success!",
        titleColor: "text-green-500"
      }
    when :error
      { border: "border-red-400",
        icon: "fa-regular fa-circle-xmark text-red-400",
        title: "Error!",
        titleColor: "text-red-500"
      }
    when :warning
      { border: "border-yellow-500",
        icon: "fa-solid fa-triangle-exclamation text-yellow-500",
        title: "Warning!",
        titleColor: "text-yellow-600"
      }
    when :notice
      { border: "border-blue-500",
        icon: "fa-solid fa-circle-info text-blue-500",
        title: "Notice!",
        titleColor: "text-blue-700"
      }
    when :alert
      { border: "border-yellow-500",
        icon: "fa-solid fa-triangle-exclamation text-yellow-500",
        title: "Alert!",
        titleColor: "text-yellow-600"
      }
    else
      { border: "border-green-400",
        icon: "fa-regular fa-circle-check text-green-400",
        title: "Success!",
        titleColor: "text-green-500"
      }
    end
  end
end

app/views/dashboard/home.html.erb
<div class="relative max-h-screen w-full flex flex-col items-center">
  <div class="h-full overflow-y-auto mb-26">
    <%= turbo_frame_tag :new_post, src: new_form_posts_path, class: "flex justify-center self-stretch" %>
    <%= turbo_frame_tag :posts, src: posts_path, class: "flex flex-col items-center justify-center self-stretch" %>
  </div>
</div>

app/views/dashboard/my_questions.html.erb
<div class="relative max-h-screen w-full flex flex-col items-center">
  <div class="h-full overflow-y-auto mb-26">
    <%= turbo_frame_tag :new_post, src: new_form_posts_path, class: "flex justify-center self-stretch" %>
    <%= turbo_frame_tag :posts, src: posts_path(user_id: current_user.id), class: "flex flex-col items-center justify-center self-stretch" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="flex flex-1 self-stretch">
  <head>
    <title><%= content_for(:title) || "Estatesearch Challenge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://kit.fontawesome.com/d136be8d5b.js" data-mutate-approach="sync"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-blue-200 flex w-screen h-screen overflow-hidden flex-col">
    <%= turbo_frame_tag :turbo_modal %>
    <%= render "shared/flash_message" %>
    <%= render "shared/header" %>
    <main class="pt-5 flex flex-col flex-1 self-stretch items-center justify-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_lock.html.erb
<% if post.locked? %>
  <div class="mr-2">
    Locked
  </div>
  <%= link_to pay_posts_path(id: post.id), data: {turbo_frame: :turbo_modal}  do %>
    <div class="flex items-center rounded-full bg-gray-300 h-8 w-16 px-0.5 cursor-pointer">
      <div class="h-7 w-7 flex items-center justify-center bg-white rounded-full border border-gray-400">
        <i class="fa-solid fa-lock text-gray-500"></i>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="mr-2 text-blue-600">
    Unlocked
  </div>

  <div class="flex items-center justify-end rounded-full bg-blue-200 border border-blue-400 h-8 w-16 px-0.5 cursor-pointer">
    <div class="h-7 w-7 flex items-center justify-center bg-white rounded-full border border-blue-400">
      <i class="fa-solid fa-lock text-blue-500"></i>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag post, class: "mt-4 w-1/2 min-w-90" do %>
  <div class="bg-white rounded-lg border border-gray-300 shadow p-3">
    <div class="flex flex-1 items-center">
      <div class="rounded-full w-10 h-10 flex items-center justify-center"
        style="background-color: <%= get_color_from(post.user.email) %>"
      >
        <div class="text-white text-xl font-satoshiMedium">
          <%= post.user.email[0].upcase%>
        </div>
      </div>
      <div class="flex flex-1 flex-col ml-3">
        <div class="font-satoshiMedium">
          <%= post.user.email %>
        </div>
        <div class="font-satoshiThin text-gray-500">
          Student -
          <%= post.created_at.strftime('%b %e, %Y') %>
        </div>
      </div>
      <div class="flex flex-row items-center">
        <%= render "posts/lock", post: post %>
      </div>
    </div>
    <div class="my-3">
      <h2 class="font-satoshiBold text-gray-800 text-xl">
        <%= post.title %>
      </h2>
      <div class="text-gray-500">
        <%= post.body %>
      </div>
    </div>
    <div class="flex">
      <div class="flex px-2 items-center rounded-l-full border border-gray-400 h-8 bg-gray-200">
        <div class="font-satoshiMedium text-gray-500 mr-4">
          <i class="fa-regular fa-thumbs-up text-gray-400"></i>
          Upvote
        </div>
        <div class="text-gray-600">
          0
        </div>
      </div>
      <div class="flex px-2 items-center rounded-r-full border border-gray-400 h-8 bg-gray-200">
        <div class="text-gray-600">
          <i class="fa-regular fa-thumbs-down text-gray-400"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend :posts,
  partial: "posts/post",
  locals: {
    post: @post
  } %>

<%= turbo_stream.append(:flash_messages,
    partial: 'shared/flash_message',
    locals: { flash: {success: "Your question has been submitted."}}) %>

<%= turbo_stream.replace :turbo_modal do %>
  <%= turbo_frame_tag :turbo_modal %>
<% end %>

app/views/posts/index.html.erb
<%= turbo_frame_tag :posts do %>
  <%= render @posts %> 
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/turbo_modal' do %>
  <div class="flex flex-col px-2 py-4 w-[600px]">
    <div class="text-xl text-gray-800 font-satoshiBold flex flex-1 justify-center">
      <h1>Add a question</h1>
    </div>
    <div class="flex items-center flex-row p-2">
      <div class="rounded-full w-10 h-10 flex items-center justify-center"
        style="background-color: <%= get_color_from(current_user.email) %>"
      >
        <div class="text-white text-xl font-satoshiMedium">
          <%= current_user.email[0].upcase%>
        </div>
      </div>
      <div class="ml-2">
        <div class="font-satoshiMedium text-lg text-gray-800">
          <%= current_user.email %>
        </div>
        <div class="text-gray-500">
          Student
        </div>
      </div>
    </div>
    <%= form_with(
          model: @post,
          url: posts_path
        ) do |form| %>
      <div class="mx-2">
        <div>
          <%= form.text_field :title,
            placeholder: "What is your question?",
            autofocus: true,
            class: "w-full text-xl font-satoshiBold h-10 text-gray-800"
          %>
        </div>
        <div>
          <%= form.text_area :body,
            placeholder: "Write something...",
            class: "w-full text-gray-700 min-h-28 max-h-56 font-satoshiMedium"
          %>
        </div>
      </div>
      <div class="border-t border-gray-300 flex justify-end pt-2">
        <div class="flex">
          <div
            class="text-gray-600 font-satoshiBold px-4 py-2 rounded-full hover:bg-gray-200 cursor-pointer"
            data-action="click->turbo-modal#close"
          >
            Cancel
          </div>
          <%= submit_tag "Add question",
            class: "bg-blue-600 rounded-full py-2 px-4 text-white font-satoshiMedium cursor-pointer hover:bg-blue-500" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/new_form.html.erb
<%= turbo_frame_tag(:new_post) do %>
  <div class="mt-4 w-1/2 min-w-90">
    <div class="bg-white p-3 flex rounded-lg border border-gray-300 shadow">
      <div class="pr-2 pt-2">
        <div class="rounded-full w-12 h-12 flex items-center justify-center"
             style="background-color: <%= get_color_from(current_user.email) %>"
          >
          <div class="text-white text-2xl font-satoshiMedium">
            <%= current_user.email[0].upcase%>
          </div>
        </div>
      </div>
      <div class="flex flex-col flex-1">
        <%= link_to new_post_path, data: {action: "click->modal#open", turbo_frame: :turbo_modal } do %>
          <input
            class="h-16 px-4 bg-gray-200 rounded-md border border-gray-300 w-full font-satoshiMedium text-gray-800"
            placeholder="What would you like to know?"
          />
        <% end %>
        <div class="text-blue-500 text-md mt-2 cursor-pointer">
          <i class="fa-solid fa-earth-americas"></i>
          Any lawyer can reply to this question
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/pay.html.erb
<%= render 'shared/turbo_modal' do %>
  <div class="flex flex-col px-4 py-4 w-[400px]">
    <div class="text-xl text-gray-800 font-satoshiBold flex flex-1 justify-center">
      <h1>Unlock this answer</h1>
    </div>
    <div class="flex items-center justify-center flex-row p-2">
      <div class="rounded-full bg-blue-200 w-28 h-28 border border-blue-400 flex items-center justify-center">
        <i class="fa-solid fa-lock fa-4x text-blue-500"></i>
      </div>
    </div>
    <div class="flex flex-col items-center justify-center my-2">
      <div class="text-xl font-satoshiMedium text-gray-800">
        Proposed fee
      </div>
      <div class="text-2xl font-satoshiBlack text-gray-800">
        £20
      </div>
    </div>

    <div class="flex flex-col items-center justify-center">
      <div class="text-md font-satoshiMedium text-gray-400">
        The content of this post will become available after you unlock this answer.
      </div>
    </div>

    <div class="flex flex-col items-center justify-center mt-2">
      <%= link_to "Pay now",
        unlock_posts_path(id: @post.id),
        data: { turbo_method: :post },
        class: "bg-indigo-500 text-white w-full rounded-md h-12 flex items-center justify-center text-lg font-satoshiBold"
      %>
    </div>
  </div>
<% end %>

app/views/posts/unlock.turbo_stream.erb
<%= turbo_stream.replace @post,
  partial: "posts/post",
  locals: {
    post: @post
  } %>

<%= turbo_stream.append(:flash_messages,
    partial: 'shared/flash_message',
    locals: { flash: {success: "Your question has been unlocked."}}) %>

<%= turbo_stream.replace :turbo_modal do %>
  <%= turbo_frame_tag :turbo_modal %>
<% end %>

app/views/shared/_flash_message.html.erb
<%= turbo_stream_from :flash_messages %>
<%= turbo_frame_tag :flash_messages do %>
  <div class="absolute right-3 bottom-5 z-50 w-96">
    <% flash.map do |type, message| %>
      <% colorClass = getFlashColorClasses(type) %>
      <div data-controller='flash-message'
        class="mb-4"
        >
        <div data-flash-message-target="container"
             class="relative flex flex-row bg-white rounded-lg pl-5 pr-12 py-5 shadow-xl drop-shadow-xl border-l-4 ring-1 ring-gray-200 animate-bounce <%= colorClass[:border] %>">
          <div data-flash-message-target="close"
            data-action="click->flash-message#close"
            class="absolute right-3 top-1 cursor-pointer">
            <i class="fa-solid fa-times text-gray-400"></i>
          </div>
          <div class="flex flex-row items-center">
            <div class="mr-4">
              <i class="<%= colorClass[:icon] %> fa-2x"></i>
            </div>
            <div class="flex flex-col max-w-80">
              <div class="<%= colorClass[:titleColor] %> font-satoshiBlack mr-1">
                <%= colorClass[:title] %>
              </div>
              <div>
                <%= sanitize message %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<% if current_user.present? %>
  <% nav_links = [{
    name: "Home",
    path: authenticated_root_path,
    show: true
  }, {
    name: "My Questions",
    path: my_questions_path,
    show: !current_user.lawyer? 
  }, {
    name: "My Answers",
    path: my_answers_path,
    show: current_user.lawyer? 
  }] %>

  <div class="flex self-stretch h-16 min-h-16 shadow drop-shadow items-center px-4 justify-between bg-white">
    <div class="flex flex-1 self-stretch items-center justify-center ">
      <% nav_links.each do |nav_link| %>
        <% next unless nav_link[:show] %>
        <% active = current_page? nav_link[:path] %>
        <%= link_to nav_link[:path],
          class: "flex self-stretch items-center px-6 mx-2 cursor-pointer border-b-3 #{active ? "border-blue-400" : "hover:border-gray-300 border-transparent"}" do %>
          <div class="font-satoshiMedium text-lg">
            <%= nav_link[:name] %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <div class="text-blue-500 hover:underline font-satoshiMedium">
          Log out
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_turbo_modal.html.erb
<%= turbo_frame_tag :turbo_modal do %>
  <div class="absolute inset-0 flex z-40 justify-center items-center"
    data-controller="turbo-modal"
    data-turbo-modal-target="modal"
  >
    <div class="flex items-center justify-center">
      <div class="relative flex flex-col flex-1 bg-white shadow drop-shadow rounded-xl z-10">
        <div class="absolute right-4 top-4">
          <div class="px-2 py-1 rounded-md hover:bg-gray-200 cursor-pointer"
            data-action="click->turbo-modal#close"
          >
            <i class="fa-solid fa-close text-blue-900"
            ></i>
          </div>
        </div>
        <%= yield %>
      </div>
    </div>
    <div class="absolute flex flex-1 bg-blue-900 opacity-40 w-full h-full"
      data-action="click->turbo-modal#close"
    ></div>
  </div>
<% end %>